# Generated by Django 3.2.4 on 2021-06-08 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0002_destination_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Masjid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='pics')),
                ('Location', models.CharField(max_length=100)),
                ('Jamat', models.CharField(max_length=100)),
                ('desc', models.TextField()),
            ],
        ),
    ]
