# Generated by Django 3.2.4 on 2021-06-07 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='author',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
